package common.dto;

public enum Command {

    C2S_SEND_PRIVATE_MESSAGE,
    S2C_SEND_PRIVATE_MESSAGE_NACK,
    S2C_SEND_PRIVATE_MESSAGE_ACK,
    S2C_RECEIVE_A_PRIVATE_MESSAGE,

    C2S_GET_FRIEND_LIST,
    C2S_GET_GROUP_LIST,

    C2S_SEND_ADD_FRIEND_OFFER_TO_FRIENDS,
    S2C_SEND_ADD_FRIEND_OFFERS_TO_FRIENDS_ACK,
    S2C_SEND_ADD_FRIEND_OFFERS_TO_FRIENDS_NACK,
    S2C_SEND_ADD_FRIEND_OFFERS_TO_FRIENDS_FAIL,

    S2C_NOTIFY_NEW_FRIEND_OFFER,
    S2C_NOTIFY_NEW_MESSAGE,

    S2C_USER_NOT_FOUND,

    C2S_FIND_FRIEND_BY_KEYWORD,
    S2C_FIND_FRIEND_BY_KEYWORD_ACK,
    S2C_FIND_FRIEND_BY_KEYWORD_NACK,

    C2S_FIND_GROUP_BY_KEYWORD,
    S2C_FIND_GROUP_BY_KEYWORD_ACK,
    S2C_FIND_GROUP_BY_KEYWORD_NACK,

    C2S_SEND_JOIN_GROUPS,
    S2C_SEND_JOIN_GROUPS_ACK,
    S2C_SEND_JOIN_GROUPS_NACK,

    S2C_GET_FRIEND_LIST_ACK,
    S2C_GET_GROUP_LIST_ACK,
    S2C_GET_GROUP_LIST_NACK,

    S2C_GET_FRIEND_LIST_NACK,

    C2S_LOGIN,
    S2C_LOGIN_ACK,
    S2C_LOGIN_NACK,

    C2S_REGISTER,
    S2C_REGISTER_ACK,
    S2C_REGISTER_NACK,

    C2S_PING,
    S2C_PING_OK,

    //    C2S_EXIT,
    C2S_GET_UNSEEN_FRIEND_OFFERS,
    S2C_GET_UNSEEN_FRIEND_OFFERS_ACK,
    S2C_GET_UNSEEN_FRIEND_OFFERS_NACK,

    C2S_SEND_ACCEPT_FRIEND_OFFERS,
    S2C_SEND_ACCEPT_FRIEND_OFFERS_ACK,
    S2C_SEND_ACCEPT_FRIEND_OFFERS_NACK,

    C2S_SEND_IGNORE_FRIEND_OFFERS,
    S2C_SEND_IGNORE_FRIEND_OFFERS_ACK,
    S2C_SEND_IGNORE_FRIEND_OFFERS_NACK,

    C2S_SEND_UNFRIEND_REQUEST,
    S2C_SEND_UNFRIEND_REQUEST_ACK,
    S2C_SEND_UNFRIEND_REQUEST_NACK,

    // Logout
    C2S_LOGOUT,

    C2S_GET_PRIVATE_MESSAGES,
    S2C_GET_PRIVATE_MESSAGES_ACK,
    S2C_GET_PRIVATE_MESSAGES_NACK,

    S2S_SEND_PRIVATE_FILE,
    S2S_SEND_PRIVATE_FILE_ACK,
    S2S_SEND_PRIVATE_FILE_NACK,
    S2C_RECEIVE_FILE,

    SERVER_STOP_SIGNAL,


    // GROUP
    C2S_LEAVE_GROUP,
    S2C_LEAVE_GROUP_ACK,
    S2C_LEAVE_GROUP_NACK,

    C2S_ADD_MEMBER_TO_GROUP,
    S2C_ADD_MEMBER_TO_GROUP_ACK,
    S2C_ADD_MEMBER_TO_GROUP_NACK,
    C2S_GET_ALL_MEMBERS_IN_GROUP,
    S2C_GET_ALL_MEMBERS_IN_GROUP_ACK,
    S2C_GET_ALL_MEMBERS_IN_GROUP_NACK,

    C2S_CREATE_NEW_GROUP,
    S2C_CREATE_NEW_GROUP_ACK,
    S2C_CREATE_NEW_GROUP_NACK,

    C2S_ACCEPT_A_MEMBER_TO_GROUP,
    S2C_ACCEPT_A_MEMBER_TO_GROUP_ACK,
    S2C_NEW_ACCEPTED_GROUP,
    S2C_ACCEPT_A_MEMBER_TO_GROUP_NACK,

    C2S_ADD_ADMIN,
    S2C_ADD_ADMIN_ACK,
    S2C_ADD_ADMIN_NACK,

    C2S_REMOVE_ADMIN,
    S2C_REMOVE_ADMIN_ACK,
    S2C_REMOVE_ADMIN_NACK,

    C2S_GET_GROUP_MESSAGES,
    S2C_GET_GROUP_MESSAGES_ACK,
    S2C_GET_GROUP_MESSAGES_NACK,

    // Send messages
    C2S_SEND_GROUP_MESSAGE,
    S2S_SEND_GROUP_MESSAGE_ACK,
    S2S_SEND_GROUP_MESSAGE_NACK,

    C2S_GET_PENDING_USER_GROUP_LIST,
    S2C_GET_PENDING_USER_GROUP_LIST_ACK,
    S2C_GET_PENDING_USER_GROUP_LIST_NACK,

    C2S_REMOVE_MEMBER,
    S2C_REMOVE_MEMBER_ACK,
    S2C_REMOVE_MEMBER_NACK,

    C2S_DECLINE_USER,
    S2C_DECLINE_USER_ACK,
    S2C_DECLINE_USER_NACK,

    S2C_NOTIFY_NEW_FRIEND,

    S2C_RECEIVE_A_GROUP_MESSAGE


}