package common.dto;

public enum Command {

    C2S_SEND_PRIVATE_MESSAGE,
    S2C_SEND_PRIVATE_MESSAGE_NACK,
    S2C_SEND_PRIVATE_MESSAGE_ACK,
    S2C_RECEIVE_A_PRIVATE_MESSAGE,


    C2S_SEND_GROUP_MESSAGE,
    S2S_SEND_GROUP_MESSAGE,

    C2S_GET_FRIEND_LIST,
    C2S_GET_GROUP_LIST,

    C2S_GET_UNSEEN_NOTIFICATIONS,
    S2C_GET_UNSEEN_NOTIFICATION_ACK,
    S2C_GET_UNSEEN_NOTIFICATION_NACK,

    C2S_MARK_SEEN_NOTIFICATIONS,


    C2S_SEND_ADD_FRIEND_OFFER_TO_FRIENDS,
    S2C_SEND_ADD_FRIEND_OFFERS_TO_FRIENDS_ACK,
    S2C_SEND_ADD_FRIEND_OFFERS_TO_FRIENDS_NACK,
    S2C_SEND_ADD_FRIEND_OFFERS_TO_FRIENDS_FAIL,


    S2C_NOTIFY_NEW_FRIEND_OFFER,
    S2C_NOTIFY_NEW_MESSAGE,


    S2C_USER_NOT_FOUND,
    C2S_FIND_FRIEND_BY_KEYWORD,

    S2C_FIND_FRIEND_BY_KEYWORD_ACK,
    S2C_FIND_FRIEND_BY_KEYWORD_NACK,

    S2C_GET_FRIEND_LIST_ACK,
    S2C_GET_GROUP_LIST_ACK,
    S2C_GET_FRIEND_LIST_NACK,

    C2S_LOGIN,
    S2C_LOGIN_ACK,
    S2C_LOGIN_NACK,

    C2S_REGISTER,
    S2C_REGISTER_ACK,
    S2C_REGISTER_NACK,

    C2S_PING,
    S2C_PING_OK,


    //    C2S_EXIT,
    C2S_GET_UNSEEN_FRIEND_OFFERS,
    S2C_GET_UNSEEN_FRIEND_OFFERS_ACK,
    S2C_GET_UNSEEN_FRIEND_OFFERS_NACK,

    C2S_SEND_ACCEPT_FRIEND_OFFERS,
    S2C_SEND_ACCEPT_FRIEND_OFFERS_ACK,
    S2C_SEND_ACCEPT_FRIEND_OFFERS_NACK,

    C2S_SEND_IGNORE_FRIEND_OFFERS,
    S2C_SEND_IGNORE_FRIEND_OFFERS_ACK,
    S2C_SEND_IGNORE_FRIEND_OFFERS_NACK,

    C2S_SEND_UNFRIEND_REQUEST,
    S2C_SEND_UNFRIEND_REQUEST_ACK,
    S2C_SEND_UNFRIEND_REQUEST_NACK,

    // Logout
    C2S_LOGOUT,
    C2S_SEND_TO_MESSAGE,

    C2S_GET_PRIVATE_MESSAGES,
    S2C_GET_PRIVATE_MESSAGES_ACK,
    S2C_GET_PRIVATE_MESSAGES_NACK,

    S2S_SEND_PRIVATE_FILE,
    S2S_SEND_PRIVATE_FILE_ACK,
    S2S_SEND_PRIVATE_FILE_NACK,
    S2C_RECEIVE_FILE,

//    S2C_EXIT;

}